### ISSUE TITLE
Inoperable code

### ISSUE THREAD

**Issue by weixunxie** [ShenZheng2000/MATH_32_HW1#3]
I have connected Anaconda to VSCode and installed the 'code' command in PATH, but it still cannot run the code. When I type some command at the terminal, it always said that "zsh: command not found", or "can't find the files". Is there anything wrong? Thank you!
<img width="947" alt="截屏2023-06-24 12 34 08" src="https://github.com/ShenZheng2000/MATH_32_HW1/assets/130762808/62b70b1b-a6d7-467f-9cec-564a8222589f">

**Comment by ShenZheng2000** [comment]
You should first `cd` to the directory where you place the file `main_q1.py`. For example,

```
cd shenzheng
```

Then you run this in terminal:

```
python main_q1.py --model lenet
```

**Comment by weixunxie** [comment]
Thanks so much! I solved it. 

But I meet another problem: 
Traceback (most recent call last):
  File "/Users/xieweixun/Desktop/main_q1.py", line 308, in <module>
    run()
  File "/Users/xieweixun/Desktop/main_q1.py", line 263, in run
    model_name = args.model.lower()
AttributeError: 'Namespace' object has no attribute 'model'

Is that mean I need to add some parameters?

<img width="1440" alt="截屏2023-06-25 14 47 35" src="https://github.com/ShenZheng2000/MATH_32_HW1/assets/130762808/aa96fcdd-6b92-40f6-a425-6501ea3433cd">

**Comment by ShenZheng2000** [comment]
The command line you've entered is not accurate. As previously indicated, you should first navigate to the desired directory using 'cd', and then execute the following command **without making any alterations** to it:

```
python main_q1.py --model lenet
```

**Comment by weixunxie** [comment]
I still didn't solve the problem, could you help me with my mistake again? Thanks!

<img width="701" alt="截屏2023-06-25 19 52 20" src="https://github.com/ShenZheng2000/MATH_32_HW1/assets/130762808/fec3eba4-65a4-4a37-9e4f-34bb13fb35ef">

**Comment by ShenZheng2000** [comment]
I suspect that you accidentally change my starter code related to argparse. Please make sure that the following are unchanged. You can redownload `main_q1.py` from this github repository for comparison. 

```
import argparse
```

```
def parse_arguments():
    parser = argparse.ArgumentParser(description='MNIST Classification')
    parser.add_argument('--model', choices=['lenet', 'alexnet'], help='Model name (lenet or alexnet)', required=True)
    parser.add_argument('--lr', type=float, default=0.001, help='Learning rate (default: 0.001)')
    parser.add_argument('--batch_size', type=int, default=64, help='Batch size (default: 64)')
    parser.add_argument('--num_epochs', type=int, default=10, help='Number of epochs (default: 10)')
    parser.add_argument('--val_split', type=float, default=0.1, help='Validation split ratio (default: 0.1)')
    return parser.parse_args()

```

**Comment by weixunxie** [comment]
I have solved this problem! Thanks so much!
